name: cforest-rtd

channels:
  - defaults
  - timmens

dependencies:
  - python=3.7
  - cforest
  - pip:
    - sphinx=2.2.1
    - sphinx_rtd_theme=0.4.3
    - nbsphinx=0.4.3
    - jupyter=1.0.0
    - numpy
    - pandas
    - sklearn
